<?php

namespace OrganizationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends EntityRepository
{
    /**
     * @param array $criteria
     * @param int   $page
     * @param int   $limit
     *
     * @return Paginator
     */
    public function findPaginated(array $criteria = [], $sort = [], $page = 1, $limit = 10)
    {
        $qb = $this->createQueryBuilder('_o');

        $offset = ($page * $limit) - $limit;
        $qb->setFirstResult($offset);
        $qb->setMaxResults($limit);

        return new Paginator($qb);
    }
}
